session_name: workspace
start_directory: ~/workspace
windows:
  - window_name: dropbox
    panes:
    - shell_command:
      - cd ~/Dropbox/
  - window_name: math
    panes:
    - shell_command:
      - R -q
  - window_name: platform
    panes:
    - shell_command:
      - cd platform
  - window_name: portal
    layout: main-vertical
    panes:
    - shell_command:
      - cd portal
    - shell_command:
      - cd portal
      - vim .
