session_name: workspace
start_directory: ~/workspace
windows:
  - window_name: hugo-docs
    panes:
    - shell_command:
      - cd ~/Dropbox/hugo-docs
      - vim .
  - window_name: math
    panes:
    - shell_command:
      - R
  - window_name: platform
    panes:
    - shell_command:
      - cd platform
      - foreman s
  - window_name: portal
    layout: main-vertical
    panes:
    - shell_command:
      - cd portal
      - yarn start
    - shell_command:
      - cd portal
      - vim .
