session_name: workspace
start_directory: ~/workspace
windows:
  - window_name: hugo-docs
    panes:
    - shell_command:
      - cd ~/Dropbox/hugo-docs
      - vim .
  - window_name: platform
    panes:
    - shell_command:
      - cd platform
      - sudo foreman s
  - window_name: top-scheduler
    panes:
    - shell_command:
      - cd top-scheduler
      - sudo foreman s
  - window_name: portal
    layout: main-vertical
    panes:
    - shell_command:
      - cd portal
      - sudo yarn start
    - shell_command:
      - cd portal
      - vim .
