session_name: workspace
start_directory: ~/workspace
windows:
  - window_name: dropbox
    panes:
    - shell_command:
      - cd ~/Dropbox/
  - window_name: math
    panes:
    - shell_command:
      - R -q
  - window_name: workspace
